# exampleNet_params.py
# Automatically generated by Netflux on 26-Oct-2022
import numpy as np


def loadParams():
    # species parameters
    speciesNames = ['A', 'B', 'C', 'D', 'E', ]
    tau = np.array([1, 1, 1, 1, 1, ])
    ymax = np.array([1, 1, 1, 1, 1, ])
    y0 = np.array([0, 0, 0, 0, 0, ])

    # reaction parameters
    w = np.array([0, 0, 1, 1, 1, 1, ])
    n = np.array([1.400000e+00, 1.400000e+00, 1.400000e+00, 1.400000e+00, 1.400000e+00, 1.400000e+00, ])
    EC50 = np.array([5.000000e-01, 5.000000e-01, 5.000000e-01, 5.000000e-01, 5.000000e-01, 5.000000e-01, ])
    return speciesNames, tau, ymax, y0, w, n, EC50