# exampleNet_params.py
# Automatically generated by Netflux on 26-Oct-2022
import numpy as np


def loadParams(diabetic=False):
    # species parameters
    speciesNames = ['insulin', 'IR', 'IRS1', 'PKB', 'mTORC1', 'GLUT4', 'glucose']
    tau = np.ones(len(speciesNames))
    ymax = np.ones(len(speciesNames))
    y0 = np.zeros(len(speciesNames))

    # reaction parameters
    w = np.ones(9)
    w[0] = 0  # insulin is an input --> means w=0????
    n = np.ones(9) * 1.4
    EC50 = np.ones(9) * 0.5

    if diabetic:
        w[1] *= 0.55  # point 1
        w[8] *= 0.5  # point 2
        w[3] *= 0.15  # point 3

    return speciesNames, tau, ymax, y0, w, n, EC50
