# exampleNet_run.py
# Automatically generated by Netflux on 26-Oct-2022
# 10/26 edits made by JS, need to incorporate into exportPythonODE.m

import numpy as np
import scipy.integrate
import matplotlib.pyplot as plt
import insulinNet
import insulinParams

if __name__ == '__main__':
    [speciesNames, tau, ymax, y0, w, n, EC50] = insulinParams.loadParams()

    # Run multistep simulation
    tspan = [0, 10]
    w[0] = 1
    sol1 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, y0, args=(tau, ymax, w, n, EC50,))
    w[0] = 0
    sol2 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, sol1.y[:, -1], args=(tau, ymax, w, n, EC50,))
    w[1] = 1
    sol3 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, sol2.y[:, -1], args=(tau, ymax, w, n, EC50,))
    w[1] = 0
    sol4 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, sol3.y[:, -1], args=(tau, ymax, w, n, EC50,))
    w[0] = 1
    w[1] = 1
    sol5 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, sol4.y[:, -1], args=(tau, ymax, w, n, EC50,))

    t = np.hstack((sol1.t, sol2.t + 10, sol3.t + 20, sol4.t + 30, sol5.t + 40))
    y = np.hstack((sol1.y, sol2.y, sol3.y, sol4.y, sol5.y))
    plt.plot(t, y.T)  # current 'ax' is getting other lines, so it causes later errors
    plt.xlabel('Time')
    plt.ylabel('Fractional activity')
    plt.legend(speciesNames)
    plt.show()
    # hi mo
