# exampleNet_params.py
# Automatically generated by Netflux on 26-Oct-2022
import numpy as np


def loadParams():
    # species parameters
    speciesNames = ['insulin', 'IR\'', 'IR', 'IRS1', 'PKB', 'mTORC1', 'GLUT4', 'glucose']
    tau = np.ones(len(speciesNames))
    ymax = np.ones(len(speciesNames))
    y0 = np.zeros(len(speciesNames))

    # reaction parameters
    w = np.ones(10)
    w[0] = 0  # insulin is an input --> means w=0????
    n = np.ones(10) * 1.4
    EC50 = np.ones(10) * 0.5
    return speciesNames, tau, ymax, y0, w, n, EC50
