# exampleNet_run.py
# Automatically generated by Netflux on 26-Oct-2022
# 10/26 edits made by JS, need to incorporate into exportPythonODE.m

import numpy as np
import scipy.integrate
import matplotlib.pyplot as plt
import insulinNet
import insulinParams


def base_sim(speciesNames, tau, ymax, y0, w, n, EC50):
    # Run multistep simulation
    tspan = [0, 10]
    w[0] = 1
    sol1 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, y0, args=(tau, ymax, w, n, EC50,))
    w[0] = 0
    sol2 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, sol1.y[:, -1], args=(tau, ymax, w, n, EC50,))
    sol3 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, sol2.y[:, -1], args=(tau, ymax, w, n, EC50,))
    w[0] = 1
    sol4 = scipy.integrate.solve_ivp(insulinNet.ODEfunc, tspan, sol3.y[:, -1], args=(tau, ymax, w, n, EC50,))

    return sol1, sol2, sol3, sol4

if __name__ == '__main__':
    [speciesNames, tau, ymax, y0, w, n, EC50] = insulinParams.loadParams()

    plt.figure()

    sol1, sol2, sol3, sol4 = base_sim(speciesNames, tau, ymax, y0, w, n, EC50)

    t = np.hstack((sol1.t, sol2.t + 10, sol3.t + 20, sol4.t + 30))
    y = np.hstack((sol1.y, sol2.y, sol3.y, sol4.y))
    plt.plot(t, y[:6].T)  # current 'ax' is getting other lines, so it causes later errors
    plt.xlabel('Time')
    plt.ylabel('Fractional activity')
    plt.legend(speciesNames)
    plt.title('Fractional activity of internal proteins')
    plt.show()

    [speciesNames, tau, ymax, y0, w, n, EC50] = insulinParams.loadParams(diabetic=True)
    sol1d, sol2d, sol3d, sol4d = base_sim(speciesNames, tau, ymax, y0, w, n, EC50)

    plt.figure()
    t = np.hstack((sol1.t, sol2.t + 10, sol3.t + 20, sol4.t + 30))
    y = np.hstack((sol1.y, sol2.y, sol3.y, sol4.y))
    plt.plot(t, y[6].T)  # current 'ax' is getting other lines, so it causes later errors

    yd = np.hstack((sol1d.y, sol2d.y, sol3d.y, sol4d.y))
    td = np.hstack((sol1d.t, sol2d.t + 10, sol3d.t + 20, sol4d.t + 30))
    plt.plot(td, yd[6].T)  # current 'ax' is getting other lines, so it causes later errors

    plt.xlabel('Time')
    plt.ylabel('Glucose uptake')
    plt.legend(["Normal", "Diabetic"])
    plt.title('Diabetic vs Normal glucose uptake')
    plt.show()

    # hi mo
